#
#Mon Aug 11 08:38:30 EDT 2025
copyright=Copyright (c) 2015-2017 Red Hat, Inc. and others.
description=Source code for Migration Toolkit for Applications (MTA) Eclipse plugin.
descriptionURL=http\://www.jboss.org/jbossdeveloperstudio/migration
featureName=Migration Toolkit for Applications (MTA) Source
license=Red Hat, Inc. licenses these features and plugins to you under certain open source licenses (or aggregations of such licenses), which in a particular case may include the Eclipse Public License, the GNU Lesser General Public License, and/or certain other open source licenses. For precise licensing details, consult the corresponding source code, or contact Red Hat, Attn\: General Counsel, 100 East Davie St., Raleigh NC 27601 USA.
licenseURL=http\://www.eclipse.org/legal/epl-v10.html
providerName=Red Hat
